export const NEW_TRANSACTION = 'NEW_TRANSACTION';
export const DEVICE_STATUS = 'DEVICE_STATUS';
export const JOB_INITIATED = 'JOB_INITIATED';
export const JOB_COMPLETED = 'JOB_COMPLETED';
export const JOB_DESTROYED = 'JOB_DESTROYED';
export const CLUSTER_CREATION_FAILED= 'CLUSTER_CREATION_FAILED';
export const CLUSTER_CREATION_SUCCESS= 'CLUSTER_CREATION_SUCCESS';
export const DEVICE_CONNECTION_FAILED = 'DEVICE_CONNECTION_FAILED';
export const DEVICE_CONNECTION_SUCCESS = 'DEVICE_CONNECTION_SUCCESS';
export const WITHDRAWAL_SUCCESS= 'WITHDRAWAL_SUCCESS';
export const RELOAD_COMPLETED= 'RELOAD_COMPLETED';
export const REWARDS_EARNED= 'REWARDS_EARNED';



export const CONTACT_EMAIL = 'CONTACT_EMAIL';
export const SITE_URL = 'SITE_URL';
export const MAIL_FROM = 'MAIL_FROM';
export const MAIL_HOST = 'MAIL_HOST';
export const MAIL_PASSWORD = 'MAIL_PASSWORD';
export const MAIL_PORT = 'MAIL_PORT';
export const MAIL_USER = 'MAIL_USER';

export const FCM_PROJECT_ID = 'FCM_PROJECT_ID';
export const FCM_CLIENT_EMAIL = 'FCM_CLIENT_EMAIL';
export const FCM_PRIVATE_KEY = 'FCM_PRIVATE_KEY';
export const HTTP_TIMEOUT = 'HTTP_TIMEOUT';
export const HTTP_MAX_REDIRECTS = 'HTTP_MAX_REDIRECTS';
